
year_tax = int(input())

BASKETBALL_SHOES = year_tax - (year_tax* 0.4)
BASKETBALL_EQUIP = BASKETBALL_SHOES - (BASKETBALL_SHOES * 0.2)
BASKETBALL_BALL = BASKETBALL_EQUIP / 4
BASKETBALL_ACCESOARIES = BASKETBALL_BALL / 5


total_spending = year_tax + BASKETBALL_SHOES + BASKETBALL_EQUIP + BASKETBALL_BALL + BASKETBALL_ACCESOARIES

print(f'{total_spending:.2f}')